apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rating-service
  template:
    metadata:
      labels:
        app: rating-service
    spec:
      containers:
        - name: rating-service
          image: gen4ralz/rating-service:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: rating-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8082
  selector:
    app: rating-service
