apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: metadata-service
  template:
    metadata:
      labels:
        app: metadata-service
    spec:
      containers:
        - name: metadata-service
          image: gen4ralz/metadata-service:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: metadata-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8081
  selector:
    app: metadata-service
